apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ include "ha-tester.fullname" . }}-pdb"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "ha-tester.fullname" . }}"
